### ISSUE TITLE
No Module "flatten_batch"

### ISSUE THREAD

**Issue by ulucsahin** [nielsrolf/tensorflow-lrp#1]
I think it is missing.

**Comment by nielsrolf** [comment]
I will look into it in the evening

**Comment by nielsrolf** [comment]
Can you post the code you tried to execute, and also how you were importing the module? `flatten_batch` is defined in `lrp/train.py l.73`

**Comment by ulucsahin** [comment]
Mistake on my part.

**Comment by nielsrolf** [comment]
I updated the examples in /examples, there is only one notebook now and I checked that it works on a machine where I cloned it for the first time. There is also a nicer plotting function.
Let me know if you have problems with anything else, as far as I know, you are the first person other than me to use it so you might discover bugs or find the docs not sufficient.

**Comment by ulucsahin** [comment]
Okay, thanks.
